name: example
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  path: ^1.8.0
  dot_report:
    path: ..
  string_eval:
    git: https://github.com/claudiodriussi/string_eval.git
  expressions:

dev_dependencies:
  lints: ^1.0.0
  test:
