name: dot_report
description: A report system for character based printers, mainly ESC/POS
version: 0.9.0
homepage: https://github.com/claudiodriussi/dot_report

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
