name: dr_flutter2
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dot_report:
    path: ../..
  flutter_bluetooth_printer: ^2.8.0
  expressions:
  yaml: ^3.1.0
  intl: ^0.17.0
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dot_report/
    - assets/images/
